language: python
python: 3.6

before_install:
  - pip install -U pip pipenv
install:
  - pipenv install --deploy --system
script:
  - pipenv run python main.py

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/pipenv"

notifications:
  slack:
    rooms:
      secure: klUILxOVvn3noDVSOlLvYlO0AfKX8wXdZi/Y3EE/GiLNHNWXY1PV1N0tawY1fiNmCzhe+I/8Er7YZjjfzxxj1KziWIGBKgq3dRbNBcuHQ0XQNp+N4nFanpG2qYEoeg07sFoPa8RKPAfbY/ivSCCcpDeqISkpuVGQXa1odkSdhcKuqJc/2e35jpkzCEGALQkdT+8/Oxj0r97YckHCd/LiC9z7YtyIY/FnXI6RB2ahwoaqiTcsqmcv7QHrwK3UbQ5UPn6hpp4+iG9imzIn+ZRgoCZKPicVZQk5NqvnGPHY5hQ3eg+TrnpEvLu4ZPHN6LVg8HsfcnMLPpSpXjwfT2RIFxetLiAu0QLsGEthX9uyWBkRkXi2olYDlOCAEWJOoXoIKJhkYDjLpDm7pSIL4qqTzdZN9uHV8ARgy1AWaqaCEmRNXNINyd/4av0k7qG/yZ1fBBKqEe6VdZ6y2uKDEnGbFdgw+jvNFGBY8nAjBcyQiU4E4HfMDL1GmAfmeYVpgmTRYwkwSt1qshMTBrTDSodv1heCSOZ8YFZb8F+Rpmy/GUPpAK+nstkj+rAZA5P2IZ/616Jis+P2KZBbCdJ/YomQurTGSo+tjhHRjb1hZIh0jGHGjgHlVB4s2wabE6pyFq4VCdoVgj3o8AsRaGMKnCObb5LqTJuPWZaB4pr+IbyUL3Q=
    on_success: always
